import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { Plus, ArrowRight, Truck, Package, FileText, CheckCircle2, XCircle, Eye } from 'lucide-react';
import { Link } from 'react-router-dom';

type StockTransfer = {
  id: string;
  transfer_number: string;
  from_branch_id: string;
  to_branch_id: string;
  status: string;
  notes: string | null;
  requested_at: string;
  approved_at: string | null;
  from_branch: { name: string; code: string };
  to_branch: { name: string; code: string };
};

export default function StockTransfers() {
  const { user, isAdmin, isBranchManager, userBranchId } = useAuth();
  const queryClient = useQueryClient();
  const [isRequestDialogOpen, setIsRequestDialogOpen] = useState(false);
  const [selectedFromBranch, setSelectedFromBranch] = useState<string>('');
  const [selectedProducts, setSelectedProducts] = useState<{ productId: string; quantity: number }[]>([]);
  const [notes, setNotes] = useState('');

  const { data: branches } = useQuery({
    queryKey: ['branches'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('branches')
        .select('*')
        .eq('is_active', true)
        .order('display_order');
      if (error) throw error;
      return data;
    },
  });

  const { data: transfers, isLoading } = useQuery({
    queryKey: ['stock-transfers'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('stock_transfers')
        .select(`
          *,
          from_branch:from_branch_id (name, code),
          to_branch:to_branch_id (name, code)
        `)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data as unknown as StockTransfer[];
    },
  });

  const { data: products } = useQuery({
    queryKey: ['products-for-transfer', selectedFromBranch],
    queryFn: async () => {
      if (!selectedFromBranch) return [];
      const { data, error } = await supabase
        .from('products')
        .select('id, name, sku, stock_quantity')
        .eq('branch_id', selectedFromBranch)
        .eq('is_active', true)
        .gt('stock_quantity', 0)
        .order('name');
      if (error) throw error;
      return data;
    },
    enabled: !!selectedFromBranch,
  });

  const createTransferMutation = useMutation({
    mutationFn: async () => {
      if (!userBranchId || !selectedFromBranch || selectedProducts.length === 0) {
        throw new Error('Missing required fields');
      }

      // Create the transfer
      const { data: transfer, error: transferError } = await supabase
        .from('stock_transfers')
        .insert({
          from_branch_id: selectedFromBranch,
          to_branch_id: userBranchId,
          requested_by: user?.id,
          notes,
          transfer_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (transferError) throw transferError;

      // Create transfer items
      const items = selectedProducts.map((p) => ({
        transfer_id: transfer.id,
        product_id: p.productId,
        requested_quantity: p.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('stock_transfer_items')
        .insert(items);

      if (itemsError) throw itemsError;

      return transfer;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['stock-transfers'] });
      setIsRequestDialogOpen(false);
      setSelectedFromBranch('');
      setSelectedProducts([]);
      setNotes('');
      toast.success('Stock transfer request created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create transfer request: ' + error.message);
    },
  });

  const getStatusBadge = (status: string) => {
    const styles: Record<string, string> = {
      requested: 'bg-blue-500',
      challan_created: 'bg-purple-500',
      approved: 'bg-emerald-500',
      in_transit: 'bg-amber-500',
      received: 'bg-cyan-500',
      completed: 'bg-green-600',
      rejected: 'bg-destructive',
    };
    return (
      <Badge className={styles[status] || 'bg-gray-500'}>
        {status.replace('_', ' ').toUpperCase()}
      </Badge>
    );
  };

  const incomingTransfers = transfers?.filter((t) => t.to_branch_id === userBranchId);
  const outgoingTransfers = transfers?.filter((t) => t.from_branch_id === userBranchId);

  const addProduct = (productId: string) => {
    if (!selectedProducts.find((p) => p.productId === productId)) {
      setSelectedProducts([...selectedProducts, { productId, quantity: 1 }]);
    }
  };

  const updateQuantity = (productId: string, quantity: number) => {
    setSelectedProducts(
      selectedProducts.map((p) =>
        p.productId === productId ? { ...p, quantity: Math.max(1, quantity) } : p
      )
    );
  };

  const removeProduct = (productId: string) => {
    setSelectedProducts(selectedProducts.filter((p) => p.productId !== productId));
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Stock Transfers</h1>
          <p className="text-muted-foreground">Request and manage stock transfers between branches</p>
        </div>
        {isBranchManager && (
          <Dialog open={isRequestDialogOpen} onOpenChange={setIsRequestDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                Request Transfer
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl">
              <DialogHeader>
                <DialogTitle>Request Stock Transfer</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <label className="text-sm font-medium">Request From Branch</label>
                  <Select value={selectedFromBranch} onValueChange={setSelectedFromBranch}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select branch to request from" />
                    </SelectTrigger>
                    <SelectContent>
                      {branches
                        ?.filter((b) => b.id !== userBranchId)
                        .map((branch) => (
                          <SelectItem key={branch.id} value={branch.id}>
                            {branch.name}
                          </SelectItem>
                        ))}
                    </SelectContent>
                  </Select>
                </div>

                {selectedFromBranch && (
                  <>
                    <div>
                      <label className="text-sm font-medium">Select Products</label>
                      <Select onValueChange={addProduct}>
                        <SelectTrigger>
                          <SelectValue placeholder="Add product to request" />
                        </SelectTrigger>
                        <SelectContent>
                          {products
                            ?.filter((p) => !selectedProducts.find((sp) => sp.productId === p.id))
                            .map((product) => (
                              <SelectItem key={product.id} value={product.id}>
                                {product.name} ({product.stock_quantity} available)
                              </SelectItem>
                            ))}
                        </SelectContent>
                      </Select>
                    </div>

                    {selectedProducts.length > 0 && (
                      <div className="border rounded-lg p-4 space-y-3">
                        <h4 className="font-medium">Selected Products</h4>
                        {selectedProducts.map((sp) => {
                          const product = products?.find((p) => p.id === sp.productId);
                          return (
                            <div key={sp.productId} className="flex items-center gap-3">
                              <span className="flex-1">{product?.name}</span>
                              <Input
                                type="number"
                                value={sp.quantity}
                                onChange={(e) => updateQuantity(sp.productId, parseInt(e.target.value))}
                                className="w-24"
                                min={1}
                                max={product?.stock_quantity || 1}
                              />
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => removeProduct(sp.productId)}
                              >
                                <XCircle className="h-4 w-4" />
                              </Button>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    <div>
                      <label className="text-sm font-medium">Notes (Optional)</label>
                      <Textarea
                        value={notes}
                        onChange={(e) => setNotes(e.target.value)}
                        placeholder="Add any notes for this transfer request"
                      />
                    </div>

                    <Button
                      onClick={() => createTransferMutation.mutate()}
                      disabled={selectedProducts.length === 0 || createTransferMutation.isPending}
                      className="w-full"
                    >
                      {createTransferMutation.isPending ? 'Creating...' : 'Submit Request'}
                    </Button>
                  </>
                )}
              </div>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <Tabs defaultValue={isBranchManager ? 'incoming' : 'all'}>
        <TabsList>
          {isAdmin && <TabsTrigger value="all">All Transfers</TabsTrigger>}
          {isBranchManager && (
            <>
              <TabsTrigger value="incoming">Incoming Requests</TabsTrigger>
              <TabsTrigger value="outgoing">Outgoing Requests</TabsTrigger>
            </>
          )}
        </TabsList>

        <TabsContent value="all" className="mt-4">
          <TransferTable transfers={transfers} getStatusBadge={getStatusBadge} isLoading={isLoading} />
        </TabsContent>

        <TabsContent value="incoming" className="mt-4">
          <TransferTable transfers={incomingTransfers} getStatusBadge={getStatusBadge} isLoading={isLoading} showActions="incoming" />
        </TabsContent>

        <TabsContent value="outgoing" className="mt-4">
          <TransferTable transfers={outgoingTransfers} getStatusBadge={getStatusBadge} isLoading={isLoading} showActions="outgoing" />
        </TabsContent>
      </Tabs>
    </div>
  );
}

function TransferTable({
  transfers,
  getStatusBadge,
  isLoading,
  showActions,
}: {
  transfers?: StockTransfer[];
  getStatusBadge: (status: string) => JSX.Element;
  isLoading: boolean;
  showActions?: 'incoming' | 'outgoing';
}) {
  if (isLoading) {
    return (
      <div className="flex justify-center py-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <Card>
      <CardContent className="pt-6">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Transfer #</TableHead>
              <TableHead>From</TableHead>
              <TableHead></TableHead>
              <TableHead>To</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Requested</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {transfers?.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                  No transfers found
                </TableCell>
              </TableRow>
            ) : (
              transfers?.map((transfer) => (
                <TableRow key={transfer.id}>
                  <TableCell className="font-mono">{transfer.transfer_number}</TableCell>
                  <TableCell>
                    <Badge variant="outline">{transfer.from_branch?.code}</Badge>
                    <span className="ml-2 text-sm">{transfer.from_branch?.name}</span>
                  </TableCell>
                  <TableCell>
                    <ArrowRight className="h-4 w-4 text-muted-foreground" />
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">{transfer.to_branch?.code}</Badge>
                    <span className="ml-2 text-sm">{transfer.to_branch?.name}</span>
                  </TableCell>
                  <TableCell>{getStatusBadge(transfer.status)}</TableCell>
                  <TableCell className="text-muted-foreground">
                    {format(new Date(transfer.requested_at), 'dd MMM yyyy')}
                  </TableCell>
                  <TableCell>
                    <Link to={`/admin/stock-transfers/${transfer.id}`}>
                      <Button variant="ghost" size="sm">
                        <Eye className="h-4 w-4 mr-1" />
                        View
                      </Button>
                    </Link>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
